//
// GameAPI.mm — AUTO-GENERATED by Il2CppDumper / CodmOffsetsExporter.
// Build label: Output
// Generated:   2026-05-20T10:29:36Z
//
// Do NOT hand-edit. Re-run the dumper to regenerate.
//
// Initializers use `getRealOffset(VA)` — the menu's existing helper
// that applies the dyld slide to an absolute VA from this build. All
// values below come from THIS particular CODM binary; ship the file
// only with a dylib built against the same game version.
//

#include "GameAPI.hpp"
#include "Utilities/Macros.h"   // getRealOffset

// ---- Method pointers ------------------------------------------------
void* (*GameAPI::GetMainCamera)() = (void* (*)())getRealOffset(0x10844E600);
void* (*GameAPI::GetComponentTransform)(void*) = (void* (*)(void*))getRealOffset(0x1084540C0);
void (*GameAPI::GetTransformPosition)(void*, Vector3*) = (void (*)(void*, Vector3*))getRealOffset(0x1084D3440);
Matrix4x4 (*GameAPI::GetWorldToCameraMatrix)(void*) = (Matrix4x4 (*)(void*))getRealOffset(0x10844DDDC);
Matrix4x4 (*GameAPI::GetProjectionMatrix)(void*) = (Matrix4x4 (*)(void*))getRealOffset(0x10844DEC4);
void* (*GameAPI::GetGameInstance)() = (void* (*)())getRealOffset(0x102960368);
void* (*GameAPI::GetLocalPawn)() = (void* (*)())getRealOffset(0x102980774);
float (*GameAPI::GetHealth)(void*) = (float (*)(void*))getRealOffset(0x1026AC920);
bool (*GameAPI::GetIsFiring)(void*) = (bool (*)(void*))getRealOffset(0x101E7C1A0);
bool (*GameAPI::GetIsAiming)(void*) = (bool (*)(void*))getRealOffset(0x101E70AAC);
void (*GameAPI::SetAimRotation)(void*, Quaternion) = (void (*)(void*, Quaternion))getRealOffset(0x101E9B5A0);
Quaternion (*GameAPI::GetAimRotation)(void*) = (Quaternion (*)(void*))getRealOffset(0x101E8703C);
uint32_t (*GameAPI::GetTeamId)(void*) = (uint32_t (*)(void*))getRealOffset(0x101E8B5C4);
Vector3 (*GameAPI::GetPawnVelocity)(void*) = (Vector3 (*)(void*))getRealOffset(0x101DC86CC);
void (*GameAPI::SetCameraFov)(void*, float) = (void (*)(void*, float))getRealOffset(0x10844D100);
bool (*GameAPI::PhysicsRaycast3)(Vector3, Vector3, float) = (bool (*)(Vector3, Vector3, float))getRealOffset(0x10849B16C);

// ---- Field offsets --------------------------------------------------
uint64_t GameAPI::kOffsetNickName = 0x158;
uint64_t GameAPI::kOffsetEnemyPawns = 0x178;
uint64_t GameAPI::kOffsetPlayerInfo = 0x5C0;
uint64_t GameAPI::kOffsetHeadBone = 0x308;
uint64_t GameAPI::kOffsetIsAlive = 0x548;
uint64_t GameAPI::kOffsetIsRobot = 0x288;
uint64_t GameAPI::kOffsetAttackableInfo = 0x78;
uint64_t GameAPI::kOffsetMaxHealth = 0x38;
