//
// GameAPI.hpp — AUTO-GENERATED by Il2CppDumper / CodmOffsetsExporter.
// Do NOT hand-edit. Re-run the dumper to regenerate.
//
// Declares every IL2CPP function pointer + field offset the DarkLuna
// menu needs. Initializers live in GameAPI.mm.
//
#pragma once

#include <cstdint>
#include "Helper/Matrix4x4.h"
#include "Helper/Quaternion.hpp"
#include "Helper/Vector3.h"

class GameAPI {
public:
    // ---- Method pointers --------------------------------------------
    static void* (*GetMainCamera)();
    static void* (*GetComponentTransform)(void*);
    static void (*GetTransformPosition)(void*, Vector3*);
    static Matrix4x4 (*GetWorldToCameraMatrix)(void*);
    static Matrix4x4 (*GetProjectionMatrix)(void*);
    static void* (*GetGameInstance)();
    static void* (*GetLocalPawn)();
    static float (*GetHealth)(void*);
    static bool (*GetIsFiring)(void*);
    static bool (*GetIsAiming)(void*);
    static void (*SetAimRotation)(void*, Quaternion);
    static Quaternion (*GetAimRotation)(void*);
    static uint32_t (*GetTeamId)(void*);
    static Vector3 (*GetPawnVelocity)(void*);
    static void (*SetCameraFov)(void*, float);
    static bool (*PhysicsRaycast3)(Vector3, Vector3, float);

    // ---- Field offsets ----------------------------------------------
    static constexpr const char* kkOffsetNickNameClass = "PlayerInfo";
    static constexpr const char* kkOffsetEnemyPawnsClass = "BaseGame";
    static constexpr const char* kkOffsetPlayerInfoClass = "Pawn";
    static constexpr const char* kkOffsetHeadBoneClass = "Pawn";
    static constexpr const char* kkOffsetIsAliveClass = "Pawn";
    static constexpr const char* kkOffsetIsRobotClass = "PlayerInfo";
    static constexpr const char* kkOffsetAttackableInfoClass = "AttackableTarget";
    static constexpr const char* kkOffsetMaxHealthClass = "AttackableTargetInfo";
    static uint64_t kOffsetNickName;
    static uint64_t kOffsetEnemyPawns;
    static uint64_t kOffsetPlayerInfo;
    static uint64_t kOffsetHeadBone;
    static uint64_t kOffsetIsAlive;
    static uint64_t kOffsetIsRobot;
    static uint64_t kOffsetAttackableInfo;
    static uint64_t kOffsetMaxHealth;
};
