//
// ExtGameAPI.m — External CODM data reader via mach_vm_read.
//
// Reads IL2CPP structures from CODM memory. All VAs come from GameAPI.mm
// (generated by the PC dumper). Since we can't call CODM functions,
// we decode ARM64 instructions to find static field addresses, then
// read cached data stored in Unity objects.
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#include <string.h>
#include <stdio.h>
#include <math.h>

#import "ExtGameAPI.h"
#import "ExternalRead.h"

// ---- VA constants (from GameAPI.mm, GL 1.0.55) ----
// These are absolute VAs. At runtime: real = ext_codm_base() + (VA - 0x100000000)
#define VA_GET_GAME_INSTANCE     0x102960368
#define VA_GET_LOCAL_PAWN        0x102980774
#define VA_GET_HEALTH            0x1026AC920
#define VA_GET_TEAM_ID           0x101E8B5C4
#define VA_GET_MAIN_CAMERA       0x10844E600
#define VA_GET_W2C_MATRIX        0x10844DDDC
#define VA_GET_PROJ_MATRIX       0x10844DEC4

// ---- Field offsets (version-specific, from GameAPI.mm) ----
#define OFF_ENEMY_PAWNS   0x178   // BaseGame → List<Pawn>
#define OFF_PLAYER_INFO   0x5C0   // Pawn → PlayerInfo
#define OFF_NICK_NAME     0x158   // PlayerInfo → string
#define OFF_HEAD_BONE     0x308   // Pawn → headBone Transform
#define OFF_IS_ALIVE      0x548   // Pawn → bool
#define OFF_IS_ROBOT      0x288   // PlayerInfo → bool
#define OFF_ATTACKABLE    0x78    // Pawn → AttackableTarget
#define OFF_MAX_HEALTH    0x38    // AttackableTargetInfo → float

// IL2CPP List<T> structure
#define OFF_LIST_ITEMS    0x10    // List → _items (Il2CppArray*)
#define OFF_LIST_SIZE     0x18    // List → _size (int32)
#define OFF_ARRAY_ELEMS   0x20    // Il2CppArray → elements[0]

// IL2CPP UnityEngine.Object → native C++ pointer
#define OFF_CACHED_PTR    0x10

// Bone offsets (from BoneMap.h)
#define OFF_BONE_MAP      0xA8
#define OFF_BONE_ARR      0x10
#define OFF_BONE_TFM      0x40

static const uint64_t kBoneOffsets[16] = {
    0x20, 0x28, 0x30, 0x38, 0x40, 0x48, 0x50, 0x58,
    0x60, 0x68, 0x70, 0x78, 0x80, 0x88, 0x90, 0x98
};

// Unity Transform cached world position (Unity 2022+).
#define OFF_TRANSFORM_POS  0x90

#define MAX_ENEMIES 32

static ExtMatrix4    g_vpMatrix;
static ExtEnemyData  g_enemies[MAX_ENEMIES];
static int           g_enemyCount = 0;
static ExtVec3       g_localPos = {0,0,0};
static uint32_t      g_localTeam = 0;

static float g_screenW = 0;
static float g_screenH = 0;

// Dynamically discovered offsets (decoded from getter functions).
static uint32_t g_teamOffset   = 0;
static uint32_t g_healthOffset = 0;
static bool     g_offsetsResolved = false;

static void pe_log(const char *fmt, ...) __attribute__((format(printf, 1, 2)));
static void pe_log(const char *fmt, ...) {
    char buf[512];
    va_list ap;
    va_start(ap, fmt);
    vsnprintf(buf, sizeof(buf), fmt, ap);
    va_end(ap);
    printf("(game) %s\n", buf);
}

// ---- Address helpers ----

static inline uint64_t va2real(uint64_t va) {
    return ext_codm_base() + (va - 0x100000000ULL);
}

static inline bool is_valid_ptr(uint64_t p) {
    return p > 0x100000000ULL && p < 0x800000000ULL;
}

// ---- ARM64 instruction decoders ----

// Decode ADRP + LDR/ADD pair to resolve the address a singleton getter loads from.
// IL2CPP singleton getters typically compile to:
//   ADRP Xd, #page
//   LDR  Xd, [Xd, #offset]   → loads pointer from static field
//   RET
static uint64_t decode_adrp_pair(uint64_t func_real_addr) {
    uint32_t insns[8];
    if (!ext_read(func_real_addr, insns, sizeof(insns))) return 0;

    for (int i = 0; i < 6; i++) {
        uint32_t adrp = insns[i];
        if ((adrp & 0x9F000000) != 0x90000000) continue;

        // ADRP immediate: immhi(19) << 2 | immlo(2), shifted left 12
        int64_t immhi = (int64_t)((adrp >> 5) & 0x7FFFF);
        if (immhi & 0x40000) immhi |= ~0x7FFFFLL;
        int64_t immlo = (adrp >> 29) & 0x3;
        int64_t imm = ((immhi << 2) | immlo) << 12;

        uint64_t pc = func_real_addr + (uint64_t)i * 4;
        uint64_t page = (pc & ~0xFFFULL) + (uint64_t)imm;

        if (i + 1 >= 8) break;
        uint32_t next = insns[i + 1];

        // LDR Xt, [Xn, #imm12] (64-bit, scaled by 8)
        if ((next & 0xFFC00000) == 0xF9400000) {
            uint32_t off12 = ((next >> 10) & 0xFFF) << 3;
            return page + off12;
        }
        // LDR Wt, [Xn, #imm12] (32-bit, scaled by 4)
        if ((next & 0xFFC00000) == 0xB9400000) {
            uint32_t off12 = ((next >> 10) & 0xFFF) << 2;
            return page + off12;
        }
        // ADD Xd, Xn, #imm12
        if ((next & 0xFF800000) == 0x91000000) {
            uint32_t off12 = (next >> 10) & 0xFFF;
            uint32_t shift = (next >> 22) & 0x3;
            if (shift == 1) off12 <<= 12;
            return page + off12;
        }
    }
    return 0;
}

// Resolve an IL2CPP singleton: decode the getter function to find the
// static field address, then read the pointer stored there.
static uint64_t resolve_singleton(uint64_t va) {
    uint64_t real = va2real(va);
    uint64_t static_addr = decode_adrp_pair(real);
    if (!static_addr || !is_valid_ptr(static_addr)) {
        pe_log("decode failed for VA 0x%llx", va);
        return 0;
    }
    uint64_t instance = ext_readptr(static_addr);
    if (!is_valid_ptr(instance)) {
        pe_log("singleton null for VA 0x%llx (field@0x%llx)", va, static_addr);
        return 0;
    }
    return instance;
}

// Decode a simple field getter to discover which struct offset it reads.
// Patterns: LDR Wt,[Xn,#off] / LDR St,[Xn,#off] / LDRB Wt,[Xn,#off]
static uint32_t decode_field_offset(uint64_t va) {
    uint32_t insns[6];
    if (!ext_read(va2real(va), insns, sizeof(insns))) return 0;

    for (int i = 0; i < 5; i++) {
        uint32_t ins = insns[i];
        // LDR Wt, [Xn, #imm12] (32-bit, scaled ×4)
        if ((ins & 0xFFC00000) == 0xB9400000)
            return ((ins >> 10) & 0xFFF) << 2;
        // LDR Xt, [Xn, #imm12] (64-bit, scaled ×8)
        if ((ins & 0xFFC00000) == 0xF9400000)
            return ((ins >> 10) & 0xFFF) << 3;
        // LDR St, [Xn, #imm12] (float, scaled ×4)
        if ((ins & 0xFFC00000) == 0xBD400000)
            return ((ins >> 10) & 0xFFF) << 2;
        // LDRB Wt, [Xn, #imm12] (byte, unscaled)
        if ((ins & 0xFFC00000) == 0x39400000)
            return (ins >> 10) & 0xFFF;
    }
    return 0;
}

// ---- Data readers ----

static ExtVec3 read_transform_pos(uint64_t transform) {
    ExtVec3 v = {0, 0, 0};
    if (!is_valid_ptr(transform)) return v;
    ext_read(transform + OFF_TRANSFORM_POS, &v, sizeof(v));
    return v;
}

static void read_enemy_bones(uint64_t pawn, ExtEnemyData *out) {
    out->bonesValid = false;

    uint64_t boneMap = ext_readptr(pawn + OFF_BONE_MAP);
    if (!is_valid_ptr(boneMap)) return;

    uint64_t arrBase = ext_readptr(boneMap + OFF_BONE_ARR);
    if (!is_valid_ptr(arrBase)) return;

    int valid = 0;
    for (int i = 0; i < 16; i++) {
        uint64_t bonePtr = ext_readptr(arrBase + kBoneOffsets[i]);
        if (!is_valid_ptr(bonePtr)) {
            out->bones[i] = (ExtVec3){0, 0, 0};
            continue;
        }

        uint64_t tfm = ext_readptr(bonePtr + OFF_BONE_TFM);
        if (!is_valid_ptr(tfm)) {
            out->bones[i] = (ExtVec3){0, 0, 0};
            continue;
        }

        out->bones[i] = read_transform_pos(tfm);
        valid++;
    }

    out->bonesValid = (valid >= 8);
}

static void read_enemy_name(uint64_t playerInfo, ExtEnemyData *out) {
    out->nameLen = 0;
    memset(out->nameUTF16, 0, sizeof(out->nameUTF16));

    uint64_t strPtr = ext_readptr(playerInfo + OFF_NICK_NAME);
    if (!is_valid_ptr(strPtr)) return;

    // IL2CPP string: { klass(8), monitor(8), length(4), chars(utf16)... }
    int32_t len = 0;
    ext_read(strPtr + 0x10, &len, 4);
    if (len <= 0 || len > 64) return;

    ext_read(strPtr + 0x14, out->nameUTF16, len * 2);
    out->nameLen = len;
}

// ---- Camera VP matrix ----

static void mat4_multiply(const float *a, const float *b, float *out) {
    for (int r = 0; r < 4; r++) {
        for (int c = 0; c < 4; c++) {
            out[r * 4 + c] =
                a[r * 4 + 0] * b[0 * 4 + c] +
                a[r * 4 + 1] * b[1 * 4 + c] +
                a[r * 4 + 2] * b[2 * 4 + c] +
                a[r * 4 + 3] * b[3 * 4 + c];
        }
    }
}

static void set_identity(ExtMatrix4 *m) {
    memset(m, 0, sizeof(*m));
    m->m[0][0] = 1; m->m[1][1] = 1;
    m->m[2][2] = 1; m->m[3][3] = 1;
}

// Try to read Camera.main and compose the VP matrix.
// Unity icalls (GetMainCamera, GetWorldToCameraMatrix, GetProjectionMatrix)
// are native C++ functions — too complex to decode instruction-by-instruction.
// Instead we attempt to resolve the Camera singleton via the IL2CPP class
// static fields, then read the matrices from the native Camera object.
static bool update_camera_matrix(void) {
    set_identity(&g_vpMatrix);

    // Attempt 1: decode GetMainCamera as an IL2CPP accessor.
    // If Camera.get_main() is a simple static field load, this works.
    // If it's a complex icall trampoline, it won't — we fall back to identity.
    uint64_t cam = resolve_singleton(VA_GET_MAIN_CAMERA);
    if (!is_valid_ptr(cam)) {
        pe_log("camera: could not resolve Camera.main");
        return false;
    }

    // The managed Camera object has m_CachedPtr at +0x10 → native Camera*.
    uint64_t nativeCam = ext_readptr(cam + OFF_CACHED_PTR);
    if (!is_valid_ptr(nativeCam)) {
        pe_log("camera: invalid native ptr (managed=0x%llx)", cam);
        return false;
    }

    // Unity native Camera stores worldToCameraMatrix and projectionMatrix
    // as cached 4×4 float arrays. Offsets are version-dependent.
    // Unity 2022 ARM64: worldToCameraMatrix ≈ 0x2C4, projectionMatrix ≈ 0x304
    // These may need calibration — the log below helps.
    const uint32_t kViewOff = 0x2C4;
    const uint32_t kProjOff = 0x304;

    float view[16], proj[16];
    if (!ext_read(nativeCam + kViewOff, view, 64) ||
        !ext_read(nativeCam + kProjOff, proj, 64)) {
        pe_log("camera: matrix read failed");
        return false;
    }

    // Sanity: a valid view matrix has non-zero elements and no NaN.
    bool sane = false;
    for (int i = 0; i < 16; i++) {
        if (view[i] != 0.0f && !isnan(view[i])) { sane = true; break; }
    }
    if (!sane) {
        pe_log("camera: view matrix all-zero or NaN (offset may be wrong)");
        return false;
    }

    // VP = View × Projection
    mat4_multiply(view, proj, (float *)g_vpMatrix.m);
    return true;
}

// ---- Dynamic offset resolution ----

static void resolve_dynamic_offsets(void) {
    if (g_offsetsResolved) return;

    g_teamOffset = decode_field_offset(VA_GET_TEAM_ID);
    if (g_teamOffset == 0) {
        pe_log("WARNING: could not decode GetTeamId offset, using fallback");
        g_teamOffset = 0x2D4; // common fallback
    } else {
        pe_log("decoded GetTeamId field offset: 0x%x", g_teamOffset);
    }

    g_healthOffset = decode_field_offset(VA_GET_HEALTH);
    if (g_healthOffset == 0) {
        pe_log("WARNING: could not decode GetHealth offset, using fallback");
        g_healthOffset = 0x3C; // common fallback
    } else {
        pe_log("decoded GetHealth field offset: 0x%x", g_healthOffset);
    }

    g_offsetsResolved = true;
}

// ---- Public API ----

void extgame_init(void) {
    CGRect screen = [UIScreen mainScreen].bounds;
    g_screenW = screen.size.width;
    g_screenH = screen.size.height;
    g_enemyCount = 0;
    g_offsetsResolved = false;
    pe_log("ExtGameAPI init: screen %.0fx%.0f", g_screenW, g_screenH);
}

int extgame_update(void) {
    g_enemyCount = 0;
    if (!ext_is_attached()) return 0;

    resolve_dynamic_offsets();
    update_camera_matrix();

    // Resolve GameInstance singleton.
    uint64_t game = resolve_singleton(VA_GET_GAME_INSTANCE);
    if (!game) {
        pe_log("update: GameInstance not found (not in match?)");
        return 0;
    }

    // Resolve local pawn for self/team filtering.
    uint64_t localPawn = resolve_singleton(VA_GET_LOCAL_PAWN);
    if (is_valid_ptr(localPawn)) {
        g_localTeam = ext_read32(localPawn + g_teamOffset);

        uint64_t headBone = ext_readptr(localPawn + OFF_HEAD_BONE);
        if (is_valid_ptr(headBone))
            g_localPos = read_transform_pos(headBone);
    }

    // Read enemy pawn list (IL2CPP List<Pawn>).
    uint64_t list = ext_readptr(game + OFF_ENEMY_PAWNS);
    if (!is_valid_ptr(list)) return 0;

    uint64_t items = ext_readptr(list + OFF_LIST_ITEMS);
    int32_t size = (int32_t)ext_read32(list + OFF_LIST_SIZE);
    if (!is_valid_ptr(items) || size <= 0) return 0;
    if (size > MAX_ENEMIES) size = MAX_ENEMIES;

    int count = 0;
    for (int i = 0; i < size; i++) {
        uint64_t pawn = ext_readptr(items + OFF_ARRAY_ELEMS + (uint64_t)i * 8);
        if (!is_valid_ptr(pawn)) continue;
        if (pawn == localPawn) continue;

        ExtEnemyData *e = &g_enemies[count];
        memset(e, 0, sizeof(*e));

        // Team — skip teammates.
        e->teamId = ext_read32(pawn + g_teamOffset);
        if (e->teamId == g_localTeam && g_localTeam != 0) continue;

        // Alive check.
        uint8_t alive = 0;
        ext_read(pawn + OFF_IS_ALIVE, &alive, 1);
        e->isAlive = (alive != 0);
        if (!e->isAlive) continue;

        // Position from head bone transform.
        uint64_t headBone = ext_readptr(pawn + OFF_HEAD_BONE);
        if (is_valid_ptr(headBone))
            e->position = read_transform_pos(headBone);

        // Health via decoded offset; max health via AttackableTarget.
        e->health = ext_readf(pawn + g_healthOffset);
        uint64_t atkInfo = ext_readptr(pawn + OFF_ATTACKABLE);
        if (is_valid_ptr(atkInfo))
            e->maxHealth = ext_readf(atkInfo + OFF_MAX_HEALTH);

        // Player info (name + bot flag).
        uint64_t playerInfo = ext_readptr(pawn + OFF_PLAYER_INFO);
        if (is_valid_ptr(playerInfo)) {
            uint8_t bot = 0;
            ext_read(playerInfo + OFF_IS_ROBOT, &bot, 1);
            e->isBot = (bot != 0);
            read_enemy_name(playerInfo, e);
        }

        // Bones.
        read_enemy_bones(pawn, e);

        e->valid = true;
        count++;
        if (count >= MAX_ENEMIES) break;
    }

    g_enemyCount = count;
    return count;
}

ExtMatrix4 extgame_get_vp_matrix(void) {
    return g_vpMatrix;
}

const ExtEnemyData* extgame_get_enemy(int index) {
    if (index < 0 || index >= g_enemyCount) return NULL;
    return &g_enemies[index];
}

ExtVec3 extgame_get_local_pos(void) {
    return g_localPos;
}

uint32_t extgame_get_local_team(void) {
    return g_localTeam;
}

bool extgame_w2s(ExtVec3 world, float *outX, float *outY) {
    const float *m = (const float *)g_vpMatrix.m;

    float clipX = world.x*m[0] + world.y*m[4] + world.z*m[8]  + m[12];
    float clipY = world.x*m[1] + world.y*m[5] + world.z*m[9]  + m[13];
    float clipW = world.x*m[3] + world.y*m[7] + world.z*m[11] + m[15];

    if (clipW < 0.001f) return false;

    float ndcX = clipX / clipW;
    float ndcY = clipY / clipW;

    *outX = (ndcX + 1.0f) * 0.5f * g_screenW;
    *outY = (1.0f - (ndcY + 1.0f) * 0.5f) * g_screenH;
    return true;
}
